### ISSUE TITLE
Déterminer le schéma de base de données

### ISSUE THREAD

**Issue by Eric-Philippe** [Mjolk-Coffee-Concept-Store/Deployment#2]
# Todo

- [ ] Déterminer les données persistantes
- [ ] Déterminer les tables, colonnes et contraintes

# Solution

- [ ] Script d'initialisation de la base de données
- [ ] MLD des tables
